# Generated by Django 3.1.2 on 2020-10-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_modul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
