# Generated by Django 3.1.2 on 2020-10-17 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_modul', '0002_auto_20201017_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='datetime',
            field=models.CharField(default=datetime.datetime(2020, 10, 17, 14, 54, 10, 658975), max_length=56),
        ),
    ]
