# Generated by Django 3.1.2 on 2020-10-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trash_modul', '0003_games_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(default='Не узаконо', max_length=86, unique=True, verbose_name='Category name')),
            ],
        ),
        migrations.AlterField(
            model_name='games',
            name='datetime',
            field=models.CharField(default='17.10.2020', max_length=40),
        ),
        migrations.AddField(
            model_name='games',
            name='cate_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trash_modul.category'),
        ),
    ]
