# Generated by Django 3.1.2 on 2020-10-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_modul', '0004_auto_20201017_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='datetime',
            field=models.CharField(default='19.10.2020', max_length=40),
        ),
        migrations.AlterField(
            model_name='games',
            name='datetime',
            field=models.CharField(default='19.10.2020', max_length=40),
        ),
    ]
