# Generated by Django 3.1.2 on 2020-11-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_modul', '0005_auto_20201019_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='datetime',
            field=models.CharField(default='16.11.2020', max_length=40),
        ),
        migrations.AlterField(
            model_name='games',
            name='datetime',
            field=models.CharField(default='16.11.2020', max_length=40),
        ),
    ]
