# Generated by Django 3.1.2 on 2020-11-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_modul', '0006_auto_20201116_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=256, verbose_name='ip')),
                ('views', models.IntegerField(verbose_name='views')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='datetime',
            field=models.CharField(default='17.11.2020', max_length=40),
        ),
        migrations.AlterField(
            model_name='games',
            name='datetime',
            field=models.CharField(default='17.11.2020', max_length=40),
        ),
    ]
