# Generated by Django 3.1.2 on 2020-11-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trash_modul', '0007_auto_20201117_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='console name')),
                ('datetime', models.CharField(default='18/11/2020', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='cate_name',
            field=models.CharField(max_length=86, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='datetime',
            field=models.CharField(default='18/11/2020', max_length=40),
        ),
        migrations.AlterField(
            model_name='games',
            name='datetime',
            field=models.CharField(default='18.11.2020', max_length=40),
        ),
        migrations.AddField(
            model_name='category',
            name='console',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trash_modul.consolename'),
        ),
    ]
