# Generated by Django 3.1.2 on 2020-11-19 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trash_modul', '0008_auto_20201118_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='console',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trash_modul.consolename'),
        ),
        migrations.AlterField(
            model_name='category',
            name='datetime',
            field=models.CharField(default='19/11/2020', max_length=40),
        ),
        migrations.AlterField(
            model_name='consolename',
            name='datetime',
            field=models.CharField(default='19/11/2020', max_length=40),
        ),
        migrations.AlterField(
            model_name='games',
            name='datetime',
            field=models.CharField(default='19.11.2020', max_length=40),
        ),
    ]
