# Generated by Django 3.1.2 on 2020-11-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_modul', '0009_auto_20201119_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
